AllCops:   
  Exclude:     
    - 'db/**/*'     
    - 'config/**/*'     
    - 'libs/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - bin/**
    - Rakefile
Documentation:
  Enabled: false