AllCops:   
  Exclude:     
    - 'db/**/*'     
    - 'config/**/*'     
    - 'libs/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - bin/**
    - Rakefile
Metrics/BlockLength:
  Enabled: true
  CountComments: false
  Exclude:
    - 'spec/**/*.rb'
    - 'config/routes.rb'
Metrics/LineLength:
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'
Documentation:
  Enabled: false